// Code generated by protoc-gen-go.
// source: proto/dura.proto
// DO NOT EDIT!

package duralib_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FileType int32

const (
	FileType_UNKNOWN   FileType = 0
	FileType_REGULAR   FileType = 1
	FileType_DIRECTORY FileType = 2
	FileType_SYMLINK   FileType = 3
)

var FileType_name = map[int32]string{
	0: "UNKNOWN",
	1: "REGULAR",
	2: "DIRECTORY",
	3: "SYMLINK",
}
var FileType_value = map[string]int32{
	"UNKNOWN":   0,
	"REGULAR":   1,
	"DIRECTORY": 2,
	"SYMLINK":   3,
}

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}
func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (x FileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *FileType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileType_value, data, "FileType")
	if err != nil {
		return err
	}
	*x = FileType(value)
	return nil
}

type ArchiveHeader struct {
	Magic              *string  `protobuf:"bytes,1,req,name=magic" json:"magic,omitempty"`
	RequiredReadFlags  []string `protobuf:"bytes,2,rep,name=required_read_flags" json:"required_read_flags,omitempty"`
	RequiredWriteFlags []string `protobuf:"bytes,3,rep,name=required_write_flags" json:"required_write_flags,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (this *ArchiveHeader) Reset()         { *this = ArchiveHeader{} }
func (this *ArchiveHeader) String() string { return proto.CompactTextString(this) }
func (*ArchiveHeader) ProtoMessage()       {}

func (this *ArchiveHeader) GetMagic() string {
	if this != nil && this.Magic != nil {
		return *this.Magic
	}
	return ""
}

type BandHead struct {
	BandNumber       *string `protobuf:"bytes,1,opt,name=band_number" json:"band_number,omitempty"`
	StartUnixtime    *int64  `protobuf:"varint,2,opt,name=start_unixtime" json:"start_unixtime,omitempty"`
	SourceHostname   *string `protobuf:"bytes,3,opt,name=source_hostname" json:"source_hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BandHead) Reset()         { *this = BandHead{} }
func (this *BandHead) String() string { return proto.CompactTextString(this) }
func (*BandHead) ProtoMessage()       {}

func (this *BandHead) GetBandNumber() string {
	if this != nil && this.BandNumber != nil {
		return *this.BandNumber
	}
	return ""
}

func (this *BandHead) GetStartUnixtime() int64 {
	if this != nil && this.StartUnixtime != nil {
		return *this.StartUnixtime
	}
	return 0
}

func (this *BandHead) GetSourceHostname() string {
	if this != nil && this.SourceHostname != nil {
		return *this.SourceHostname
	}
	return ""
}

type BandTail struct {
	BandNumber       *string `protobuf:"bytes,1,opt,name=band_number" json:"band_number,omitempty"`
	EndUnixtime      *int64  `protobuf:"varint,2,opt,name=end_unixtime" json:"end_unixtime,omitempty"`
	BlockCount       *int32  `protobuf:"varint,4,opt,name=block_count" json:"block_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BandTail) Reset()         { *this = BandTail{} }
func (this *BandTail) String() string { return proto.CompactTextString(this) }
func (*BandTail) ProtoMessage()       {}

func (this *BandTail) GetBandNumber() string {
	if this != nil && this.BandNumber != nil {
		return *this.BandNumber
	}
	return ""
}

func (this *BandTail) GetEndUnixtime() int64 {
	if this != nil && this.EndUnixtime != nil {
		return *this.EndUnixtime
	}
	return 0
}

func (this *BandTail) GetBlockCount() int32 {
	if this != nil && this.BlockCount != nil {
		return *this.BlockCount
	}
	return 0
}

type FileIndex struct {
	Path             []byte    `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	FileType         *FileType `protobuf:"varint,2,opt,name=file_type,enum=duralib.proto.FileType" json:"file_type,omitempty"`
	DataSha1         []byte    `protobuf:"bytes,3,opt,name=data_sha1" json:"data_sha1,omitempty"`
	DataLength       *int64    `protobuf:"varint,4,opt,name=data_length" json:"data_length,omitempty"`
	DataOffset       *int64    `protobuf:"varint,5,opt,name=data_offset" json:"data_offset,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *FileIndex) Reset()         { *this = FileIndex{} }
func (this *FileIndex) String() string { return proto.CompactTextString(this) }
func (*FileIndex) ProtoMessage()       {}

func (this *FileIndex) GetPath() []byte {
	if this != nil {
		return this.Path
	}
	return nil
}

func (this *FileIndex) GetFileType() FileType {
	if this != nil && this.FileType != nil {
		return *this.FileType
	}
	return 0
}

func (this *FileIndex) GetDataSha1() []byte {
	if this != nil {
		return this.DataSha1
	}
	return nil
}

func (this *FileIndex) GetDataLength() int64 {
	if this != nil && this.DataLength != nil {
		return *this.DataLength
	}
	return 0
}

func (this *FileIndex) GetDataOffset() int64 {
	if this != nil && this.DataOffset != nil {
		return *this.DataOffset
	}
	return 0
}

type BlockIndex struct {
	File             []*FileIndex `protobuf:"bytes,1,rep,name=file" json:"file,omitempty"`
	DataSha1         []byte       `protobuf:"bytes,2,opt,name=data_sha1" json:"data_sha1,omitempty"`
	DataLength       *int64       `protobuf:"varint,3,opt,name=data_length" json:"data_length,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *BlockIndex) Reset()         { *this = BlockIndex{} }
func (this *BlockIndex) String() string { return proto.CompactTextString(this) }
func (*BlockIndex) ProtoMessage()       {}

func (this *BlockIndex) GetDataSha1() []byte {
	if this != nil {
		return this.DataSha1
	}
	return nil
}

func (this *BlockIndex) GetDataLength() int64 {
	if this != nil && this.DataLength != nil {
		return *this.DataLength
	}
	return 0
}

func init() {
	proto.RegisterEnum("duralib.proto.FileType", FileType_name, FileType_value)
}
